[features]
seeds = true

[programs.localnet]
lockbox_governor = "7J1mLX2ozMwU6p6mX7zuXMoZf5SBwLBZrGevJHpXP98k"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "artifacts/id.json"

[profile.release]
overflow-checks = true

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
